### PR TITLE
Nish

### PR DESCRIPTION
**Pull request by nishant1399**
hey dear bro this is the final code please publish it

### CODE REVIEW

**Review by TheChanRProject — COMMENTED** [review]
Hi Nishant, it looks nice, but wouldn't it also be cool if we can change the 2 doctors to show up in a red color?

**Review by nishant1399 — COMMENTED** [review]
its an awesome idea

**Review by TheChanRProject — CHANGES_REQUESTED** [review]
Okay Nishant, I want you to change the 2 doctors to show up in a red color. 

Do this and I'll move your code to be published in the master branch.

**Comment by nishant1399** [comment]
do u like how i did it bro ?

**Comment by TheChanRProject** [comment]
Excellent work, bro! I'll merge it :)

**Pull request merged**
